# Generated by Django 5.2.8 on 2025-12-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='eco_temperature',
            field=models.FloatField(default=16.0),
        ),
    ]
