# Generated by Django 5.2.8 on 2025-12-13 11:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('current_temperature', models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('source', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.zone')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ManualOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_temperature', models.FloatField()),
                ('active_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('target_temperature', models.FloatField()),
                ('priority', models.PositiveIntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.zone')),
            ],
            options={
                'ordering': ['priority', 'start_time'],
                'unique_together': {('zone', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
