# Generated by Django 5.2.8 on 2025-11-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='target_temperature',
            field=models.FloatField(default=20.0),
        ),
    ]
