# Generated by Django 5.2.8 on 2025-11-28 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_zone_target_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualoverride',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_override', to='controller.zone'),
        ),
    ]
