# Generated by Django 5.2.8 on 2025-11-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_alter_manualoverride_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
