# Generated by Django 5.2.8 on 2025-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_zone_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
    ]
