# Generated by Django 5.2.8 on 2025-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_alter_schedule_options_rename_time_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_time'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='zone',
        ),
        migrations.AddField(
            model_name='schedule',
            name='zones',
            field=models.ManyToManyField(to='controller.zone'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='days_of_week',
            field=models.ManyToManyField(to='controller.dayofweek'),
        ),
    ]
